import {z} from 'zod';
import {database,getResources,getServices,allocate,resourceGuards,reservationInserts} from './server';
import {AppError,now,uuid,today,quoteClaims} from './domain';
import {TOUR_PARALLEL,parseDeparture,departureScheduleClaims,scheduleOwner,simultaneousClaims,tourSeatId,selectedDeparture} from './tour-domain';
import type {Claim} from './domain';
import type {TourDeparture,PublicDeparture,TravelRequest,Quote} from './types';
type Row={resource_id:string;slot:string;unit:number;request_id:string};
const futureSlot=()=>Math.floor(Date.now()/900000)*900000;
const FUTURE="slot LIKE 'time:%' AND CAST(substr(slot,6) AS INTEGER)>=?";
export async function getTourLimit(){const row=await database().prepare("SELECT data FROM settings WHERE id='tour-inventory'").first<{data:string}>();return row?JSON.parse(row.data).maxConcurrentTours as number:1;}
export function tourLimitGuard(limit:number){return database().prepare("INSERT INTO operations (key,at) SELECT CASE WHEN COALESCE((SELECT json_extract(data,'$.maxConcurrentTours') FROM settings WHERE id='tour-inventory'),1)=? THEN ? ELSE NULL END,?").bind(limit,'limit-check:'+uuid(),now());}
export async function getDepartures(withStats=false):Promise<TourDeparture[]>{const rows=await database().prepare('SELECT data FROM tour_departures').all<{data:string}>();const deps=rows.results.map(r=>JSON.parse(r.data) as TourDeparture).sort((a,b)=>a.start.localeCompare(b.start));if(!withStats)return deps;
 const reservations=await database().prepare("SELECT resource_id,count(*) as seats FROM reservations WHERE resource_id LIKE 'tour-seat:%' AND slot='seats' GROUP BY resource_id").all<{resource_id:string;seats:number}>();const requests=await database().prepare('SELECT data FROM requests').all<{data:string}>();const pending=requests.results.map(r=>JSON.parse(r.data) as TravelRequest).filter(r=>r.status==='enquiry');return deps.map(d=>{const booked=reservations.results.find(r=>r.resource_id===tourSeatId(d.id))?.seats||0;const requested=pending.filter(r=>(r.quote?.items||r.items).some(i=>i.departureId===d.id)).reduce((sum,r)=>sum+r.guests,0);return {...d,bookedSeats:booked,remainingSeats:Math.max(0,d.capacity-booked),requestedSeats:requested};});}
export async function publicDepartures():Promise<PublicDeparture[]>{const services=await getServices();return (await getDepartures(true)).filter(d=>d.status==='open'&&Date.parse(d.start)>Date.now()&&services.some(s=>s.id===d.serviceId&&s.published&&s.kind==='tour')).map(({id,serviceId,start,end,capacity,status,bookedSeats,remainingSeats})=>({id,serviceId,start,end,capacity,status,bookedSeats,remainingSeats}));}
export function departureGuards(deps:TourDeparture[]){return deps.map(d=>database().prepare('INSERT INTO operations (key,at) SELECT CASE WHEN EXISTS(SELECT 1 FROM tour_departures WHERE id=? AND version=?) THEN ? ELSE NULL END,?').bind(d.id,d.version,'departure-check:'+uuid(),now()));}
function rowSnapshot(rows:Row[]){return rows.map(r=>r.slot+':'+r.unit+':'+r.request_id).join('|');}
function reservationGuard(resourceId:string,rows:Row[],futureOnly=false){const sql="INSERT INTO operations (key,at) SELECT CASE WHEN COALESCE((SELECT group_concat(label,'|') FROM (SELECT slot||':'||unit||':'||request_id AS label FROM reservations WHERE resource_id=?"+(futureOnly?' AND '+FUTURE:'')+" ORDER BY slot,unit)), '')=? THEN ? ELSE NULL END,?";return database().prepare(sql).bind(resourceId,...(futureOnly?[futureSlot()]:[]),rowSnapshot(rows),'reservation-check:'+uuid(),now());}
async function rowsFor(resourceId:string,futureOnly=false){return (await database().prepare('SELECT resource_id,slot,unit,request_id FROM reservations WHERE resource_id=?'+(futureOnly?' AND '+FUTURE:'')+' ORDER BY slot,unit').bind(resourceId,...(futureOnly?[futureSlot()]:[])).all<Row>()).results;}
function packRows(rows:Row[],capacity:number){const slots=new Map<string,Row[]>();for(const row of rows){const group=slots.get(row.slot)||[];group.push(row);slots.set(row.slot,group);}const packed:Row[]=[];for(const group of slots.values()){if(group.length>capacity)throw new AppError('This limit is below the existing confirmed or scheduled capacity. Cancel or reschedule those commitments first.',409);group.forEach((r,i)=>packed.push({...r,unit:i+1}));}return packed;}
function insertRows(rows:Row[]){return reservationInserts(rows.map((r):[string,string,number,string]=>[r.resource_id,r.slot,r.unit,r.request_id]));}
async function safeBatch(statements:D1PreparedStatement[]){try{await database().batch(statements);}catch(e){if(/constraint|unique/i.test(String(e)))throw new AppError('Inventory changed while you were saving. Refresh and try again.',409);throw e;}}
export async function ensureLegacyTourClaims(){
 // Preserve tours confirmed before shared-departure/global limits were introduced.
 // Backfill operational commitments outside schema migrations, with revision guards.
 const db=database();const records=await db.prepare('SELECT data FROM requests').all<{data:string}>();const occupied=await rowsFor(TOUR_PARALLEL,true);const owners=new Set(occupied.map(r=>r.request_id));const missing=records.results.map(r=>JSON.parse(r.data) as TravelRequest).filter(r=>r.status==='confirmed'&&!owners.has(r.id)&&r.quote?.items.some(i=>!i.departureId&&r.serviceSnapshots.find(s=>s.id===i.serviceId)?.kind==='tour'&&Date.parse(i.end)>Date.now()));if(!missing.length)return;
 const extra:D1PreparedStatement[]=[reservationGuard(TOUR_PARALLEL,occupied,true)];const newRows:Row[]=[];const occupancy=new Map<string,Set<number>>();for(const row of occupied){const used=occupancy.get(row.slot)||new Set<number>();used.add(row.unit);occupancy.set(row.slot,used);}
 for(const r of missing){extra.push(db.prepare('INSERT INTO operations (key,at) SELECT CASE WHEN EXISTS(SELECT 1 FROM requests WHERE id=? AND version=? AND json_extract(data,\'$.status\')=\'confirmed\') THEN ? ELSE NULL END,?').bind(r.id,r.version,'legacy-tour:'+r.id+':'+r.quote!.id,now()));for(const item of r.quote!.items){if(item.departureId||r.serviceSnapshots.find(s=>s.id===item.serviceId)?.kind!=='tour'||Date.parse(item.end)<=Date.now())continue;for(const claim of simultaneousClaims(item.start,item.end,20).filter(c=>Number(c.slot.slice(5))>=futureSlot())){const used=occupancy.get(claim.slot)||new Set<number>();let unit=1;while(used.has(unit))unit++;used.add(unit);occupancy.set(claim.slot,used);newRows.push({resource_id:TOUR_PARALLEL,slot:claim.slot,unit,request_id:r.id});}}}
 await safeBatch([...extra,...insertRows(newRows)]);
}
export async function bookingInventory(r:TravelRequest){await ensureLegacyTourClaims();const resources=await getResources();const departures=await getDepartures();const limit=await getTourLimit();const claims=quoteClaims(r,resources,departures,limit);const relevantDeps=departures.filter(d=>r.quote?.items.some(i=>i.departureId===d.id));return {claims,guards:[...resourceGuards(resources.filter(res=>claims.some(c=>c.resourceId===res.id))),...departureGuards(relevantDeps),tourLimitGuard(limit)]};}
export async function validateRequestedDepartures(items:{serviceId:string;date:string;departureId?:string}[],guests:number){const deps=await getDepartures(true);for(const item of items){if(!item.departureId)continue;const d=deps.find(d=>d.id===item.departureId&&d.serviceId===item.serviceId&&d.status==='open'&&Date.parse(d.start)>Date.now());if(!d)throw new AppError('This tour departure is no longer open. Choose another date.');const localDate=new Date(Date.parse(d.start)+4*3600000).toISOString().slice(0,10);if(item.date!==localDate)throw new AppError('The chosen date does not match this departure.');if(guests>(d.remainingSeats||0))throw new AppError('There are not enough places left for this group. Choose another tour departure.',409);}}
export async function validateQuotedDepartures(q:Quote,r:TravelRequest):Promise<D1PreparedStatement[]>{const deps=await getDepartures();const guards:D1PreparedStatement[]=[];for(const item of q.items){if(!item.departureId)continue;if(r.serviceSnapshots.find(s=>s.id===item.serviceId)?.kind!=='tour')throw new AppError('Only a tour can use a departure.');if(item.units!==r.guests)throw new AppError('Tour departure places must match the guest count.');const d=selectedDeparture(item.departureId,item.serviceId,item.start,item.end,deps);const seats=await rowsFor(tourSeatId(d.id));if(r.guests>d.capacity-seats.length)throw new AppError('Not enough places remain on this departure. Choose another departure for the quote.',409);guards.push(...departureGuards([d]),reservationGuard(tourSeatId(d.id),seats));}return guards;}
export async function mutateInventory(input:any){
 if(!['saveDeparture','setTourLimit'].includes(input.action))return null;
 await ensureLegacyTourClaims();const db=database();const limit=await getTourLimit();
 if(input.action==='setTourLimit'){const newLimit=z.number().int().min(1).max(20).parse(input.maxConcurrentTours);const rows=await rowsFor(TOUR_PARALLEL,true);const packed=packRows(rows,newLimit);await safeBatch([tourLimitGuard(limit),reservationGuard(TOUR_PARALLEL,rows,true),db.prepare("INSERT INTO settings (id,data) VALUES ('tour-inventory',?) ON CONFLICT(id) DO UPDATE SET data=excluded.data").bind(JSON.stringify({maxConcurrentTours:newLimit})),db.prepare('DELETE FROM reservations WHERE resource_id=? AND '+FUTURE).bind(TOUR_PARALLEL,futureSlot()),...insertRows(packed)]);return {ok:true};}
 const inputDep=parseDeparture(input.departure);const deps=await getDepartures();const previous=deps.find(d=>d.id===inputDep.id);if(previous&&previous.version!==inputDep.version)throw new AppError('This departure changed. Refresh before editing.',409);if(!previous&&inputDep.version!==0)throw new AppError('New departures must start with version zero.');const services=await getServices();if(!services.some(s=>s.id===inputDep.serviceId&&s.kind==='tour'))throw new AppError('Choose a tour from the catalogue.');
 const seatRows=await rowsFor(tourSeatId(inputDep.id));const structural=previous&&(previous.serviceId!==inputDep.serviceId||Date.parse(previous.start)!==Date.parse(inputDep.start)||Date.parse(previous.end)!==Date.parse(inputDep.end)||previous.guideId!==inputDep.guideId||previous.vehicleId!==inputDep.vehicleId);
 if(seatRows.length&&(structural||inputDep.status==='cancelled'))throw new AppError('Guests are already confirmed on this departure. Cancel their bookings before changing the schedule, guide, vehicle or cancelling the departure.',409);
 if(inputDep.capacity<seatRows.length)throw new AppError(`At least ${seatRows.length} places are already confirmed. Capacity cannot be lower.`,409);
 if(inputDep.status!=='cancelled'&&Date.parse(inputDep.start)<=Date.now())throw new AppError('Schedule departures in the future. Past departure records remain available to view.');
 if(previous?.status==='cancelled'&&seatRows.length)throw new AppError('This cancelled departure has inconsistent seat records. Review bookings first.',409);
 const d:TourDeparture={...inputDep,version:previous?previous.version+1:0};const resources=await getResources();const claims=d.status==='cancelled'?[]:departureScheduleClaims(d,resources,limit);
 const allocation=await allocate(claims,scheduleOwner(d.id),scheduleOwner(d.id));const packed=packRows(seatRows,d.capacity);
 const save=previous?db.prepare('UPDATE tour_departures SET data=?,version=? WHERE id=? AND version=?').bind(JSON.stringify(d),d.version,d.id,previous.version):db.prepare('INSERT INTO tour_departures (id,data,version) VALUES (?,?,?)').bind(d.id,JSON.stringify(d),d.version);
 await safeBatch([...(previous?[...departureGuards([previous]),db.prepare('INSERT INTO operations (key,at) VALUES (?,?)').bind('departure-edit:'+d.id+':'+previous.version,now())]:[]),tourLimitGuard(limit),reservationGuard(tourSeatId(d.id),seatRows),...resourceGuards(resources.filter(res=>claims.some(c=>c.resourceId===res.id))),save,db.prepare('DELETE FROM reservations WHERE request_id=?').bind(scheduleOwner(d.id)),...allocation,db.prepare('DELETE FROM reservations WHERE resource_id=?').bind(tourSeatId(d.id)),...insertRows(packed)]);
 return {ok:true};
}
