import {env} from 'cloudflare:workers';
import {DEFAULT_SETTINGS,PROPOSED_SERVICES} from './defaults';
import {AppError,now,uuid,requestSchema,validateItems,newRequest,assertQuoteLive,serviceSchema,resourceSchema,settingsSchema,quoteSchema,createQuote,assertConfirmable,quoteClaims,resourceClaims,money,zonedInstant} from './domain';
import type {Settings,Service,Resource,TravelRequest,AvailabilityBlock} from './types';
import type {Claim} from './domain';
import {z} from 'zod';
import {bookingInventory,getTourLimit,getDepartures,mutateInventory,validateRequestedDepartures,validateQuotedDepartures} from './inventory-server';
const SITE_ORIGIN='https://mestia-mountain-travel.aware-lily-4001.chatgpt.site';
export function database(){if(!env.DB)throw new AppError('Database unavailable. Please try again later.',503);return env.DB;}
export async function getSettings():Promise<Settings>{const row=await database().prepare("SELECT data FROM settings WHERE id='business'").first<{data:string}>();return {...DEFAULT_SETTINGS,...(row?JSON.parse(row.data):{}),maxConcurrentTours:await getTourLimit()};}
async function list<T>(table:'services'|'resources'|'requests'|'blocks'):Promise<T[]>{const rows=await database().prepare(`SELECT data FROM ${table}`).all<{data:string}>();return rows.results.map(row=>JSON.parse(row.data));}
export async function getServices():Promise<Service[]>{const s=await list<Service>('services');return s.length?s:structuredClone(PROPOSED_SERVICES);}
export const getResources=()=>list<Resource>('resources');
export async function getTravelRequest(id:string){const row=await database().prepare('SELECT data FROM requests WHERE id=?').bind(id).first<{data:string}>();if(!row)throw new AppError('Request not found.',404);return JSON.parse(row.data) as TravelRequest;}
export async function byToken(token:string){if(!/^[a-f0-9-]{60,80}$/i.test(token))throw new AppError('This request link is invalid.',404);const row=await database().prepare('SELECT data FROM requests WHERE token=?').bind(token).first<{data:string}>();if(!row)throw new AppError('This request link is invalid.',404);const r=JSON.parse(row.data) as TravelRequest;if(Date.parse(r.tokenExpiresAt)<=Date.now())throw new AppError('This link has expired. Contact the operator for a fresh link.',410);return r;}
export function publicSettings(s:Settings){const {adminUserId,...publicData}=s;return publicData;}
export function identity(req:Request){return req.headers.get('oai-authenticated-user-id')||'';}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(!origin||![new URL(req.url).origin,SITE_ORIGIN].includes(origin))throw new AppError('Please submit this form from the website.',403);}
export async function body(req:Request){if(Number(req.headers.get('content-length')||0)>65536)throw new AppError('The request is too large.',413);let value:string;try{value=await req.text();if(new TextEncoder().encode(value).byteLength>65536)throw new AppError('The request is too large.',413);const parsed=JSON.parse(value);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new AppError('Submit a form object.');return parsed;}catch(e){if(e instanceof AppError)throw e;throw new AppError('Could not read the submitted form.');}}
export async function requireAdmin(req:Request){const id=identity(req);if(!id)throw new AppError('Sign in to access the owner panel.',401);const s=await getSettings();if(!s.adminUserId||s.adminUserId!==id)throw new AppError('Owner access is required.',403);return s;}
async function rateLimit(req:Request){const raw=req.headers.get('cf-connecting-ip')||identity(req)||'anonymous';const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw));const key=Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,'0')).join('')+':'+Math.floor(Date.now()/3600000);const row=await database().prepare('INSERT INTO rate_limits (key,count) VALUES (?,1) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key).first<{count:number}>();if((row?.count||0)>20)throw new AppError('Too many requests. Please try again in an hour.',429);}
function append(r:TravelRequest,event:string,actor:string){r.history.push({at:now(),event,actor});r.updatedAt=now();r.version++;return r;}
export async function saveRequest(r:TravelRequest,priorVersion:number,extra:D1PreparedStatement[]=[]){const db=database();try{await db.batch([db.prepare('INSERT INTO operations (key,at) VALUES (?,?)').bind(`${r.id}:v${priorVersion}`,now()),db.prepare('UPDATE requests SET data=?,version=?,token=? WHERE id=? AND version=?').bind(JSON.stringify(r),r.version,r.token,r.id,priorVersion),...extra]);}catch(e){const message=e instanceof Error?e.message:'';if(/constraint|unique/i.test(message))throw new AppError('This request changed or a resource was just taken. Refresh and try again.',409);throw e;}}
function replayRequest(r:TravelRequest,data:z.infer<typeof requestSchema>,source:'website'|'manual'){
 const saved={name:r.name,contact:r.contact,guests:r.guests,notes:r.notes,items:r.items,source:r.source};const submitted={name:data.name,contact:data.contact,guests:data.guests,notes:data.notes,items:data.items,source};
 if(JSON.stringify(saved)!==JSON.stringify(submitted))throw new AppError('This submission was already saved with different details. Submit the changed details as a new request.',409);
 return {reference:r.reference,token:r.token,duplicate:true};
}
export async function createTravelRequest(req:Request,input:unknown,source:'website'|'manual'='website'){
 const data=requestSchema.parse(input);
 const existing=await database().prepare('SELECT data FROM requests WHERE idempotency=?').bind(data.idempotencyKey).first<{data:string}>();if(existing)return replayRequest(JSON.parse(existing.data) as TravelRequest,data,source);
 const services=await getServices();validateItems(data,services,source==='manual');await validateRequestedDepartures(data.items,data.guests);
 if(source==='website')await rateLimit(req);
 const duplicates=await list<TravelRequest>('requests');if(duplicates.some(r=>r.contact.toLowerCase()===data.contact.toLowerCase()&&r.status==='enquiry'&&Date.parse(r.createdAt)>Date.now()-600000&&JSON.stringify(r.items)===JSON.stringify(data.items))){const replay=await database().prepare('SELECT data FROM requests WHERE idempotency=?').bind(data.idempotencyKey).first<{data:string}>();if(replay)return replayRequest(JSON.parse(replay.data) as TravelRequest,data,source);throw new AppError('A matching request was saved recently. Use its secure link or contact the operator before sending another.',409);}
 const r=newRequest(data,services,source);try{await database().prepare('INSERT INTO requests (id,token,idempotency,data,version) VALUES (?,?,?,?,0)').bind(r.id,r.token,data.idempotencyKey,JSON.stringify(r)).run();}catch(e){if(/unique/i.test(String(e))){const again=await database().prepare('SELECT data FROM requests WHERE idempotency=?').bind(data.idempotencyKey).first<{data:string}>();if(again)return replayRequest(JSON.parse(again.data) as TravelRequest,data,source);}throw e;}
 return {reference:r.reference,token:r.token};
}
export async function adminData(req:Request){const id=identity(req);if(!id)throw new AppError('Sign in to open the owner panel.',401);const s=await getSettings();if(!s.adminUserId)return {initialized:false,identity:id,settings:publicSettings(s),services:[],resources:[],requests:[],blocks:[],departures:[],tourInventory:{maxConcurrentTours:await getTourLimit()}};await requireAdmin(req);return {initialized:true,identity:id,settings:publicSettings(s),services:await getServices(),resources:await getResources(),requests:(await list<TravelRequest>('requests')).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),blocks:await list<AvailabilityBlock>('blocks'),departures:await getDepartures(true),tourInventory:{maxConcurrentTours:await getTourLimit()}};}
export async function bootstrap(req:Request){sameOrigin(req);const id=identity(req);if(!id)throw new AppError('Sign in first.',401);const s=await getSettings();if(s.adminUserId)throw new AppError('Owner access has already been set up.',409);
 // The initial claim is enabled only behind this Site's owner-private access policy.
 // Initialise before sharing or public launch. All later admin calls check this durable ID.
 try{await database().prepare('INSERT INTO settings (id,data) VALUES (?,?)').bind('business',JSON.stringify({...s,adminUserId:id})).run();}catch{throw new AppError('Owner access was already configured. Refresh.',409);}return {ok:true};}
export function resourceGuards(resources:Resource[]):D1PreparedStatement[]{const db=database();return resources.map(r=>db.prepare('INSERT INTO operations (key,at) SELECT CASE WHEN EXISTS (SELECT 1 FROM resources WHERE id=? AND data=?) THEN ? ELSE NULL END,?').bind(r.id,JSON.stringify(r),'resource-check:'+uuid(),now()));}
export type ReservationTuple=[resourceId:string,slot:string,unit:number,owner:string];
export function reservationInserts(rows:ReservationTuple[]):D1PreparedStatement[]{
 // One bounded JSON parameter avoids a SQL statement for every 15-minute slot.
 // Plain INSERT preserves unique-constraint failures and whole-batch rollback.
 const statements:D1PreparedStatement[]=[];const db=database();
 for(let i=0;i<rows.length;i+=200)statements.push(db.prepare("INSERT INTO reservations (resource_id,slot,unit,request_id) SELECT json_extract(value,'$[0]'),json_extract(value,'$[1]'),json_extract(value,'$[2]'),json_extract(value,'$[3]') FROM json_each(?)").bind(JSON.stringify(rows.slice(i,i+200))));
 return statements;
}
export async function allocate(claims:Claim[],owner:string,exclude='',excludeClaims?:Claim[]):Promise<D1PreparedStatement[]>{const db=database();const rows:ReservationTuple[]=[];const resourceIds=[...new Set(claims.map(c=>c.resourceId))];if(!resourceIds.length)return [];const released=new Set(excludeClaims?.map(c=>c.resourceId+'|'+c.slot));const occupied=await db.prepare('SELECT resource_id,slot,unit,request_id FROM reservations WHERE resource_id IN ('+resourceIds.map(()=>'?').join(',')+') AND request_id!=?').bind(...resourceIds,excludeClaims?'':exclude).all<{resource_id:string;slot:string;unit:number;request_id:string}>();const occupancy=new Map<string,Set<number>>();for(const row of occupied.results){const key=row.resource_id+'|'+row.slot;if(excludeClaims&&row.request_id===exclude&&released.has(key))continue;const used=occupancy.get(key)||new Set<number>();used.add(row.unit);occupancy.set(key,used);}for(const c of claims){const used=occupancy.get(c.resourceId+'|'+c.slot)||new Set<number>();if(used.size+c.units>c.capacity)throw new AppError(c.resourceId==='__tour_parallel__'?'The simultaneous-tour limit is reached. Choose another time or increase the limit in Inventory.':'Not enough capacity remains for this resource or tour departure.',409);const free:number[]=[];for(let unit=1;unit<=c.capacity&&free.length<c.units;unit++)if(!used.has(unit))free.push(unit);if(free.length<c.units)throw new AppError('A room, guide, driver, vehicle or seat is already reserved for this time. Choose another resource or schedule.',409);for(const unit of free)rows.push([c.resourceId,c.slot,unit,owner]);}return reservationInserts(rows);}
function taxiOnly(r:TravelRequest):TravelRequest{return {...r,items:r.items.filter(i=>r.serviceSnapshots.find(s=>s.id===i.serviceId)?.kind==='taxi'),serviceSnapshots:r.serviceSnapshots.filter(s=>s.kind==='taxi'),quote:{...r.quote!,items:r.quote!.items.filter(i=>r.serviceSnapshots.find(s=>s.id===i.serviceId)?.kind==='taxi')}};}
function taxiReleaseClaims(r:TravelRequest,resources:Resource[]):Claim[]{
 if(r.dispatch.status!=='accepted')return [];
 const claims:Claim[]=[];
 for(const item of taxiOnly(r).quote!.items){const ids=new Set([...item.resourceIds.filter(id=>{const res=resources.find(r=>r.id===id);return res&&res.kind!=='driver'&&res.kind!=='vehicle';}),r.dispatch.driverId,r.dispatch.vehicleId]);
  for(const id of ids){const res=resources.find(r=>r.id===id);if(res)claims.push(...resourceClaims({...res,active:true,capacity:Math.max(res.capacity,item.units)},item.start,item.end,item.units));}
 }
 return claims;
}
function releaseReservations(owner:string,claims:Claim[]):D1PreparedStatement[]{const statements:D1PreparedStatement[]=[];for(let i=0;i<claims.length;i+=200)statements.push(database().prepare("DELETE FROM reservations WHERE request_id=? AND (resource_id,slot) IN (SELECT json_extract(value,'$[0]'),json_extract(value,'$[1]') FROM json_each(?))").bind(owner,JSON.stringify(claims.slice(i,i+200).map(c=>[c.resourceId,c.slot]))));return statements;}
export async function mutateAdmin(req:Request,input:any){sameOrigin(req);const settings=await requireAdmin(req);const actor=identity(req);const db=database();const inventoryResult=await mutateInventory(input);if(inventoryResult)return inventoryResult;
 if(input.action==='saveSettings'){const clean=settingsSchema.parse(input.settings);await db.prepare("UPDATE settings SET data=? WHERE id='business'").bind(JSON.stringify({...clean,adminUserId:settings.adminUserId})).run();return {ok:true};}
 if(input.action==='saveService'){const clean=serviceSchema.parse(input.service);const existing=await list<Service>('services');const seed=existing.length?[]:PROPOSED_SERVICES.filter(s=>s.id!==clean.id).map(s=>db.prepare('INSERT OR IGNORE INTO services (id,data) VALUES (?,?)').bind(s.id,JSON.stringify(s)));await db.batch([...seed,db.prepare('INSERT INTO services (id,data) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(clean.id,JSON.stringify(clean))]);return {ok:true};}
 if(input.action==='saveResource'){const clean=resourceSchema.parse(input.resource);const previous=(await getResources()).find(r=>r.id===clean.id);const occupied=await db.prepare("SELECT 1 as found FROM reservations WHERE resource_id=? AND ((slot LIKE 'night:%' AND substr(slot,7)>=?) OR (slot LIKE 'time:%' AND CAST(substr(slot,6) AS INTEGER)>=?)) LIMIT 1").bind(clean.id,new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tbilisi'}).format(new Date()),Math.floor(Date.now()/900000)*900000).first();if(occupied&&previous&&(previous.kind!==clean.kind||previous.capacity!==clean.capacity||previous.bufferMinutes!==clean.bufferMinutes||previous.active!==clean.active))throw new AppError('This resource has bookings or blocks. Release or cancel those commitments before changing its capacity, timing or active state.',409);const structural=previous&&(previous.kind!==clean.kind||previous.capacity!==clean.capacity||previous.bufferMinutes!==clean.bufferMinutes||previous.active!==clean.active);try{await db.batch([...(structural?[db.prepare("INSERT INTO operations (key,at) SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM reservations WHERE resource_id=? AND ((slot LIKE 'night:%' AND substr(slot,7)>=?) OR (slot LIKE 'time:%' AND CAST(substr(slot,6) AS INTEGER)>=?))) THEN ? ELSE NULL END,?").bind(clean.id,new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tbilisi'}).format(new Date()),Math.floor(Date.now()/900000)*900000,'edit-resource:'+uuid(),now())]:[]),db.prepare('INSERT INTO resources (id,data) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(clean.id,JSON.stringify(clean))]);}catch(e){if(/constraint/i.test(String(e)))throw new AppError('This resource was just reserved. Refresh before changing its setup.',409);throw e;}return {ok:true};}
 if(input.action==='createManual')return createTravelRequest(req,input.request,'manual');
 if(input.action==='block'){const data=z.object({resourceId:z.string(),start:zonedInstant,end:zonedInstant,reason:z.string().trim().min(2).max(500)}).parse(input);const resource=(await getResources()).find(r=>r.id===data.resourceId);if(!resource)throw new AppError('Resource not found.');const block={...data,id:uuid()};const claims=resourceClaims(resource,data.start,data.end,resource.capacity);const extra=await allocate(claims,'block:'+block.id);try{await db.batch([...resourceGuards([resource]),db.prepare('INSERT INTO blocks (id,data) VALUES (?,?)').bind(block.id,JSON.stringify(block)),...extra]);}catch(e){if(/constraint|unique/i.test(String(e)))throw new AppError('This resource has just been reserved.',409);throw e;}return {ok:true};}
 if(input.action==='unblock'){const id=z.string().uuid().parse(input.blockId);await db.batch([db.prepare('DELETE FROM blocks WHERE id=?').bind(id),db.prepare('DELETE FROM reservations WHERE request_id=?').bind('block:'+id)]);return {ok:true};}
 const id=z.string().uuid().parse(input.requestId);const r=await getTravelRequest(id);const prior=r.version;let extra:D1PreparedStatement[]=[];
 if(input.action==='verifyContact'){if(r.status==='cancelled'||r.status==='completed')throw new AppError('This request is closed.');r.contactEvidence=z.string().trim().min(5).max(500).parse(input.contactEvidence);r.contactVerified=true;append(r,'Two-way contact verified: '+r.contactEvidence,actor);}
 else if(input.action==='quote'){if(r.payment.paid>0)throw new AppError('Refund verified funds before replacing the quote.');r.quote=createQuote(quoteSchema.parse(input.quote),r,settings);extra=await validateQuotedDepartures(r.quote,r);if(r.serviceSnapshots.some(s=>s.kind==='taxi'))r.dispatch={status:'unassigned',driverId:'',vehicleId:'',evidence:''};append(r,'Quote issued; guest acceptance required',actor);}
 else if(input.action==='recordPayment'||input.action==='recordRefund'){if(!r.quote)throw new AppError('Issue a quote before recording money.');if(r.status==='cancelled'&&input.action==='recordPayment')throw new AppError('Do not record new payments against a cancelled request.');const data=z.object({amount:z.number().positive().max(100000),reference:z.string().trim().min(3).max(500)}).parse(input);if(money(data.amount)<=0)throw new AppError('Record at least GEL 0.01.');const amount=money(data.amount)*(input.action==='recordRefund'?-1:1);if(r.payment.paid+amount<0)throw new AppError('Refund cannot exceed collected funds.');if(r.payment.paid+amount>r.quote.total)throw new AppError('Payment exceeds the agreed total.');r.payment.paid=money(r.payment.paid+amount);r.payment.entries.push({id:uuid(),amount,reference:data.reference,at:now()});append(r,`${amount<0?'Refund':'Verified funds'} recorded: GEL ${Math.abs(amount).toFixed(2)}; ${data.reference}`,actor);}
 else if(input.action==='dispatch'){if(!['enquiry','confirmed'].includes(r.status))throw new AppError('This request is closed.');if(!r.serviceSnapshots.some(s=>s.kind==='taxi'))throw new AppError('This request has no taxi.');const data=z.object({status:z.enum(['unassigned','offered','accepted','unavailable']),driverId:z.string().default(''),vehicleId:z.string().default(''),evidence:z.string().trim().max(500).default('')}).parse(input);if(data.status==='offered'||data.status==='accepted'){if(r.status==='confirmed'&&r.quote!.items.some(i=>r.serviceSnapshots.find(s=>s.id===i.serviceId)?.kind==='taxi'&&Date.parse(i.end)<=Date.now()))throw new AppError('This taxi trip has already ended. Keep its dispatch record and complete the booking after all services finish.');const resources=await getResources();const driver=resources.find(res=>res.id===data.driverId&&res.kind==='driver'&&res.active);const vehicle=resources.find(res=>res.id===data.vehicleId&&res.kind==='vehicle'&&res.active);if(!driver||!vehicle||vehicle.capacity<r.guests)throw new AppError('Choose an active driver and a vehicle suitable for all guests.');}
  if(data.status==='accepted'){if(r.status==='enquiry')assertQuoteLive(r);if(!r.quote?.acceptedAt)throw new AppError('Agree the fare with the guest before recording driver acceptance.');if(data.evidence.length<5)throw new AppError('Record how and when the driver accepted.');if(r.dispatch.status!=='offered'||r.dispatch.driverId!==data.driverId||r.dispatch.vehicleId!==data.vehicleId||Date.parse(r.dispatch.offerExpiresAt||'')<=Date.now())throw new AppError('Offer this driver the job first. Expired offers must be sent again.');}
  const previousDispatch=r.dispatch;r.dispatch={...data,...(data.status==='accepted'?{acceptedAt:now()}:{}),...(data.status==='offered'?{offerExpiresAt:new Date(Date.now()+1800000).toISOString()}:{} )};if(r.status==='confirmed'){const resources=await getResources();const released=taxiReleaseClaims({...r,dispatch:previousDispatch},resources);extra=releaseReservations(r.id,released);if(data.status==='accepted'){const plan=await bookingInventory(taxiOnly(r));extra=[...plan.guards,...extra,...await allocate(plan.claims,r.id,r.id,released)];}}append(r,'Taxi dispatch: '+data.status+(data.evidence?' — '+data.evidence:''),actor);}
 else if(input.action==='confirm'){assertConfirmable(r);const plan=await bookingInventory(r);extra=[...plan.guards,...await allocate(plan.claims,r.id)];r.status='confirmed';append(r,'Booking confirmed; inventory reserved',actor);}
 else if(input.action==='cancel'){if(r.status==='cancelled'||r.status==='completed')throw new AppError('This request is already closed.');const reason=z.string().trim().min(3).max(500).parse(input.reason);r.status='cancelled';r.dispatch={...r.dispatch,status:'unassigned'};extra=[db.prepare('DELETE FROM reservations WHERE request_id=?').bind(r.id)];append(r,'Cancelled: '+reason+'; review refund according to accepted terms',actor);}
 else if(input.action==='complete'){if(r.status!=='confirmed')throw new AppError('Confirm the booking before marking it completed.');if(r.quote!.items.some(i=>Date.parse(i.end)>Date.now()))throw new AppError('A service is still scheduled in the future. Mark completed after delivery.');r.status='completed';extra=[db.prepare("DELETE FROM reservations WHERE request_id=? AND resource_id NOT LIKE 'tour-seat:%'").bind(r.id)];append(r,'Services completed',actor);}
 else if(input.action==='renewLink'){r.token=crypto.randomUUID()+crypto.randomUUID().replaceAll('-','');r.tokenExpiresAt=new Date(Date.now()+180*86400000).toISOString();append(r,'Guest link renewed; old link revoked',actor);}
 else throw new AppError('Unknown owner action.');
 await saveRequest(r,prior,extra);return {ok:true};
}
export async function guestAction(req:Request,input:any){sameOrigin(req);const token=z.string().parse(input.token);const r=await byToken(token);if(input.action==='view'){const s=await getSettings();return {request:{reference:r.reference,tokenExpiresAt:r.tokenExpiresAt,name:r.name,guests:r.guests,items:r.items,serviceSnapshots:r.serviceSnapshots,status:r.status,quote:r.quote,payment:{paid:r.payment.paid,entries:[]},dispatch:{status:r.dispatch.status==='offered'&&Date.parse(r.dispatch.offerExpiresAt||'')<=Date.now()?'unassigned':r.dispatch.status},history:[]},settings:publicSettings(s)};}
 const prior=r.version;let extra:D1PreparedStatement[]=[];
 if(input.action==='accept'){if(r.status!=='enquiry')throw new AppError('This request is already confirmed or closed.');assertQuoteLive(r);if(input.quoteId!==r.quote!.id)throw new AppError('The quote has changed. Refresh and review it again.',409);if(input.acceptTerms!==true)throw new AppError('Accept the written terms to continue.');if(r.quote!.acceptedAt)return {ok:true};extra=await validateQuotedDepartures(r.quote!,r);r.quote!.acceptedAt=now();append(r,'Guest accepted quote '+r.quote!.id+' and policy '+r.quote!.policyVersion,'guest');}
 else if(input.action==='requestChange'){if(r.status==='cancelled'||r.status==='completed')throw new AppError('This request is closed.');const message=z.string().trim().min(5).max(1500).parse(input.message);append(r,'Guest requested a change or cancellation: '+message,'guest');}
 else throw new AppError('Unknown request action.');await saveRequest(r,prior,extra);return {ok:true};
}
export async function respond(action:()=>Promise<unknown>){try{return Response.json(await action(),{headers:{'Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff'}});}catch(e){if(e instanceof AppError)return Response.json({error:e.message},{status:e.status,headers:{'Cache-Control':'no-store'}});if(e instanceof z.ZodError)return Response.json({error:e.issues.map(i=>i.path.join('.')+': '+i.message).slice(0,3).join('; ')},{status:400,headers:{'Cache-Control':'no-store'}});console.error('Request operation failed:',e instanceof Error?e.message:'unknown error');return Response.json({error:'The operation could not be saved. Please try again.'},{status:500,headers:{'Cache-Control':'no-store'}});}}
