/* Browser-only teaching model. Production Flask remains the booking authority. */
(function(root){
'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tbilisi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const overlap=(a,b)=>a.start<b.end&&b.start<a.end;
const assert=(ok,message)=>{if(!ok)throw Error(message)};
function fresh(seed){return {version:1,services:clone(seed),requests:[],resources:[{id:1,name:'Guide · sample',kind:'guide',active:true},{id:2,name:'Room 1 · sample',kind:'room',active:true},{id:3,name:'Driver & vehicle · sample',kind:'driver',active:true}],blocks:[],providers:[{id:1,name:'Local host · sample',approved:true}],settings:{name:'Mestia',discount:10,offer:true,terms:'Demo terms: route and price agreed before confirmation. Contact the host for changes.'},reminders:[],history:[]}}
function log(s,text){s.history.unshift({at:new Date().toISOString(),text})}
function expire(s){for(const r of s.requests)if(r.quote&&['offered','accepted'].includes(r.quote.status)&&Date.parse(r.quote.expires)<=Date.now()){r.quote.status='expired';log(s,r.id+' quote expired')}}
function request(s,data){const svc=s.services.find(x=>x.id===Number(data.service));assert(svc&&svc.published&&!svc.archived,'Choose a published activity.');assert(data.name.trim()&&data.contact.trim(),'Add fictional name and contact details.');assert(data.start>=day()&&data.end>data.start,'Choose valid future dates; end must follow start.');assert(Number.isInteger(+data.guests)&&+data.guests>0&&+data.guests<=100,'Choose 1–100 guests.');if(data.stay){assert(s.settings.offer&&svc.kind==='tour','This offer is not available.');assert(data.checkin<=data.start&&data.checkout>=data.start&&data.checkout>data.checkin,'Tour date must fall within your stay.');assert(s.services.some(x=>x.kind==='stay'&&x.published&&!x.archived),'No demo stay is published.')}
const r={id:'DEMO-'+String(s.requests.length+1).padStart(4,'0'),...data,service:svc.id,title:svc.title_en,kind:svc.kind,guests:+data.guests,contactVerified:false,status:'new',quote:null,booking:null,payments:[],messages:[],driver:'unassigned',offer:data.stay?{percent:+s.settings.discount,checkin:data.checkin,checkout:data.checkout}:null};s.requests.unshift(r);log(s,r.id+' requested');return r}
function available(s,r,resource,start,end){expire(s);assert(s.resources.some(x=>x.id===+resource&&x.active),'Select an active resource.');assert(!s.blocks.some(b=>b.resource===+resource&&overlap({start,end},b)),'Resource is blocked for those dates.');for(const other of s.requests){if(other.id===r.id||!other.quote)continue;const held=other.booking==='confirmed'||['offered','accepted'].includes(other.quote.status);if(held)assert(!other.quote.items.some(i=>i.resource===+resource&&overlap({start,end},i)),'Resource already held or booked.')}}
function quote(s,r,items,deposit,hours,applyOffer){assert(r.booking!=='confirmed','Cancel the confirmed booking before replacing its quote.');assert(items.length&&hours>=1&&hours<=168,'Choose items and an expiry between 1 and 168 hours.');const copy=clone(items);for(const i of copy){assert(i.title.trim()&&Number.isFinite(i.price)&&i.price>=0&&Number.isInteger(i.quantity)&&i.quantity>0,'Enter item title, explicit price and quantity.');assert(i.start>=day()&&i.end>i.start,'Agree valid item dates.');available(s,r,i.resource,i.start,i.end);i.original=i.price;i.total=Math.round(i.price*100)*i.quantity}
for(let a=0;a<copy.length;a++)for(let b=a+1;b<copy.length;b++)assert(copy[a].resource!==copy[b].resource||!overlap(copy[a],copy[b]),'Two items cannot use the same resource at overlapping times.');
if(applyOffer){assert(r.offer&&copy.some(i=>i.kind==='stay'&&i.start<=r.start&&i.end>=r.start),'Include a stay covering the tour to apply the offer.');for(const i of copy)if(i.kind==='tour'){i.price=Math.round(i.price*100*(100-r.offer.percent)/100)/100;i.total=Math.round(i.price*100)*i.quantity}}
const total=copy.reduce((n,i)=>n+i.total,0);assert(Number.isFinite(deposit)&&deposit>=0&&Math.round(deposit*100)<=total,'Deposit must be between zero and the total.');r.quote={version:(r.quote?.version||0)+1,status:'offered',items:copy,total,deposit:Math.round(deposit*100),expires:new Date(Date.now()+hours*3600000).toISOString(),terms:s.settings.terms,discount:applyOffer?r.offer.percent:0};r.payments=[];r.driver='unassigned';r.status='reviewed';r.booking=null;log(s,r.id+' quote prepared')}
function paid(r){return r.payments.filter(p=>p.verified).reduce((n,p)=>n+(p.kind==='refund'?-p.amount:p.amount),0)}
function accept(s,r){expire(s);assert(r.quote?.status==='offered','No current offer to accept.');r.quote.status='accepted';log(s,r.id+' guest accepted')}
function confirm(s,r){expire(s);assert(r.quote?.status==='accepted','Guest must accept the current quote first.');assert(r.contactVerified,'Verify a two-way contact first.');assert(paid(r)>=r.quote.deposit,'Verify the required deposit first.');if(r.quote.items.some(i=>i.kind==='taxi'))assert(r.driver==='accepted','Driver must accept first.');for(const i of r.quote.items)available(s,r,i.resource,i.start,i.end);r.booking='confirmed';r.quote.status='confirmed';log(s,r.id+' booking confirmed')}
function cancel(s,r){if(r.quote)r.quote.status='cancelled';r.booking='cancelled';r.driver='cancelled';log(s,r.id+' cancelled; resources released')}
root.DemoModel={fresh,request,quote,accept,confirm,cancel,available,paid,expire,day,log};
if(typeof module!=='undefined')module.exports=root.DemoModel;
})(typeof window==='undefined'?globalThis:window);
